timeVAE:
  latent_dim: 10
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 8
  use_residual_conn: true
  trend_poly: 3
  custom_seas: null
# RSI "trend_poly": 1, "latent_dim": 10, "reconstruction_wt": 3, "learning_rate": 0.001, "batch_size": 8
# ALL "trend_poly": 3, "latent_dim": 7, "reconstruction_wt": 3, "learning_rate": 0.001, "batch_size": 8
vae_dense:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 16

vae_conv:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 16
